# docker-compose.yaml
version: '3.8'

x-default-volumes: &default-volumes
  - ${CONFIG_PATH:-./config.yaml}:/etc/fast/config.yaml:ro
  - ${SSL_PATH:-./ssl}:/etc/fast/ssl:ro
  - ${WWW_PATH:-./www}:/var/www/fast:ro
  - ${LOG_PATH:-./logs}:/var/log/fast

services:
  fast-server:
    container_name: fast-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes: *default-volumes
    environment:
      - GO_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    networks:
      - fast-network

networks:
  fast-network:
    driver: bridge